### ISSUE TITLE
setup problems: 

### ISSUE THREAD

**Issue by jrochkind** [sportngin/hubstats#119]
So, set up my app per instructions. Ran setup rake task. 

Booted app, first problem was I seemed to have no routes, just got default rails home page, and `rake routes` showed me no routes. But I looked at hubstats source, and decided I should add `mount Hubstats::Engine => "/"` to my `./config/routes.rb`. 

I did that, restarted, now when I access `/`, I get a weird error suggesting perhaps the migrations installed by `rake hubstats:install:migrations` were incomplete?
~~~
ActionView::Template::Error (PG::UndefinedColumn: ERROR:  column "pull_request_count" does not exist
LINE 1: ... '2017-04-21') GROUP BY hubstats_labels.id HAVING pull_reque...
                                                             ^
: SELECT hubstats_labels.*, COUNT(hubstats_labels_pull_requests.pull_request_id) AS pull_request_count FROM "hubstats_labels" INNER JOIN "hubstats_labels_pull_requests" ON "hubstats_labels_pull_requests"."label_id" = "hubstats_labels"."id" INNER JOIN "hubstats_pull_requests" ON "hubstats_pull_requests"."id" = "hubstats_labels_pull_requests"."pull_request_id" WHERE (hubstats_pull_requests.updated_at BETWEEN '2017-04-06' AND '2017-04-21') GROUP BY hubstats_labels.id HAVING pull_request_count > 0  ORDER BY pull_request_count DESC):
    20:
    21:       <h4> Labels </h4>
    22:       <div id="labels-container">
    23:         <% @labels.each do |label| %>
    24:           <a class="btn btn-label btn-sm" data-color="<%= label.color %>" >
    25:             <span class="circle-label pull-left"></span>
    26:             <span class="label-text pull-left" data-label="<%=label.name%>"> <%= label.name %> </span>
  activerecord (4.2.8) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
  activerecord (4.2.8) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
  activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
  activerecord (4.2.8) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
  activerecord (4.2.8) lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
  activerecord (4.2.8) lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.2.8) lib/active_record/querying.rb:39:in `find_by_sql'
  activerecord (4.2.8) lib/active_record/relation.rb:639:in `exec_queries'
  activerecord (4.2.8) lib/active_record/relation.rb:515:in `load'
  activerecord (4.2.8) lib/active_record/relation.rb:243:in `to_a'
  activerecord (4.2.8) lib/active_record/relation/delegation.rb:46:in `each'
  hubstats (0.9.5) app/views/hubstats/pull_requests/index.html.erb:23:in `___sers_jrochkind__gem_ruby_______gems_hubstats_______app_views_hubstats_pull_requests_index_html_erb___2394494810246928341_70304555659120'
  actionview (4.2.8) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.8) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.8) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.8) lib/action_view/template.rb:143:in `render'
  actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.8) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.8) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.8) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.8) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.8) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.8) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.8) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.8) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.8) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.8) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.8) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.8) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/jrochkind/.rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.8) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.8) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.8) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.8) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.8) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.8) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.8) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.8) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.8) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:817:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.8) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /Users/jrochkind/.rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/jrochkind/.rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/jrochkind/.rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
~~~

**Comment by emmasax1** [comment]
Yes, this does seem to be the case. I've never seen this error before, but I'd suggest trying to run the migrations again, and then make sure to actually place some data into your database, whether that be faking data or pulling some of your own GitHub data. Actually look into your database to make sure all of the appropriate columns exist.

**Comment by emmasax1** [comment]
Also, if it's noteworthy, we have `mount Hubstats::Engine => "/hubstats"` written into the Gemfile of the application we use.
