### ISSUE TITLE
Setup issue : ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base

### ISSUE THREAD

**Issue by javjim-mautic** [sportngin/hubstats#135]
When I run rake db:migrate I get the following issue.

Output
```root@host/var/lib/gems/2.5.0/gems/hubstats-0.11.5 $ RAILS_ENV=production rake db:migrate --trace
fatal: not a git repository (or any of the parent directories): .git
** Invoke load_app (first_time)
** Execute load_app
** Invoke db:migrate (first_time)
** Invoke load_app
** Invoke app:db:migrate (first_time)
** Invoke app:environment (first_time)
** Execute app:environment
** Invoke app:db:load_config (first_time)
** Execute app:db:load_config
** Execute app:db:migrate
rake aborted!
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:941:in `initialize'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `new'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:237:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => db:migrate => app:db:migrate
```

running ```rake db:create``` does creates the database.

Can someone help me understand what is my issue?

config/database.yml
```
production:
  adapter: mysql2
  database: blog_development
  username: root
  password: passwoooord
  host: localhost
  port: 3306
  pool: 10
```

**Comment by javjim-mautic** [comment]
used sqlite at then end,
